EPMS Forensics/Models/Investigator/SearchResults.cs
using EPMS_Forensics_Entities;
using System.Collections.Generic;

namespace EPMS_Forensics.Models.Investigator
{
    public class SearchResults
    {
        public SearchResults()
        {
            Applicants = new List<Person>();
        }

        public List<Person> Applicants { get; set; }
    }
}

EPMS Forensics/Controllers/InvestigatorController.cs
using EPMS_Forensics.Helpers;
using EPMS_Forensics.Models.Investigator;
using EPMS_Forensics_Entities;
using EPMS_Forensics_Proxy;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using Helper = EPMS_Forensics.Helpers.Helper;

namespace EPMS_Forensics.Controllers
{
    [UserAuthorized]
    public class InvestigatorController : BaseController
    {
        private static List<State> _states;
        private static List<Branch> _branches;

        #region Actions

        public ActionResult Index()
        {
            if (_branches == null)
                _branches = new InvestigatorProxy().InvestigatorChannel.GetBranches();

            if (_states == null)
                _states = new InvestigatorProxy().InvestigatorChannel.GetStates();

            // Set up branch list
            ViewBag.Branches = _branches;
            ViewBag.States = _states;

            return View();
        }

        #endregion

        #region Json

        // Search
        public ActionResult SearchByName(string surname, string firstname, string middlename, string dob, string sex, string state, string min, string max)
        {
            try
            {
                if ((string.IsNullOrEmpty(surname) && string.IsNullOrEmpty(firstname) && string.IsNullOrEmpty(middlename)) || string.IsNullOrEmpty(sex))
                    return Json(new { err = "Please enter a part of the name and gender" }, JsonRequestBehavior.AllowGet);

                var results = new SearchResults();

                // Get results
                if (Session["CurrentUser"] is Person person)
                    results.Applicants = new InvestigatorProxy().InvestigatorChannel.SearchByNameV2(surname, firstname, middlename,
                            sex, dob, state, min, max, person.PersonId);

                // filter if dob is given
                if (!string.IsNullOrEmpty(dob) && results.Applicants.Count != 0)
                {
                    var dobresult = results.Applicants.Where(x => x.Dob == DateTime.ParseExact(dob, "dd/MM/yyyy", null)).ToList();

                    if (dobresult.Count != 0)
                        results.Applicants = dobresult;
                }

                // Order by surname
                results.Applicants = results.Applicants.OrderBy(x => x.Surname).ThenBy(x => x.Middlename).ThenBy(x => x.Firstname).ToList();

                return Json(new { status = 1, num = results.Applicants.Count, page = Helper.JsonPartialView(this, "_SearchResults", results) }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                SaveError(ex);
                return Json(new { status = -1, err = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult SearchByApplication(string afisquerynum, string enrolmentid, string passportnum, string idperson, string branchid)
        {
            try
            {
                if (string.IsNullOrEmpty(afisquerynum) && string.IsNullOrEmpty(enrolmentid) && string.IsNullOrEmpty(passportnum) && string.IsNullOrEmpty(idperson) && string.IsNullOrEmpty(branchid))
                    return Json(new { err = "Invalid search criteria" }, JsonRequestBehavior.AllowGet);

                // Create enrolment string
                if (!string.IsNullOrEmpty(enrolmentid) && !string.IsNullOrEmpty(branchid))
                    enrolmentid = branchid + enrolmentid.PadLeft(9, '0');

                var person = Session["CurrentUser"] as Person;
                if (string.IsNullOrEmpty(passportnum))
                    passportnum = "";

                if (person != null)
                {
                    var results = new SearchResults
                    {
                        Applicants = new InvestigatorProxy().InvestigatorChannel.SearchByApplication(afisquerynum,
                            enrolmentid, passportnum.ToUpper(), idperson, person.PersonId)
                    };

                    // Get results
                    return Json(new { status = 1, num = results.Applicants.Count, page = Helper.JsonPartialView(this, "_SearchResults", results) }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                SaveError(ex);
                return Json(new { status = -1, err = ex.Message }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { status = 0 }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SearchBlacklist(string blacklistpassport)
        {
            try
            {
                if (string.IsNullOrEmpty(blacklistpassport))
                    return Json(new { err = "Invalid search criteria" }, JsonRequestBehavior.AllowGet);

                // Get results
                if (Session["CurrentUser"] is Person person)
                {
                    var results = new InvestigatorProxy().InvestigatorChannel.SearchBlacklist(blacklistpassport.ToUpper(), person.PersonId);

                    return Json(new { status = 1, num = results.Count, page = Helper.JsonPartialView(this, "_BlackList", results) }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { status = 0 }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                SaveError(ex);
                return Json(new { status = -1, err = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult SearchByBooklet(string tracebooklet)
        {
            try
            {
                if (string.IsNullOrEmpty(tracebooklet))
                    return Json(new { err = "Please enter a search variable" }, JsonRequestBehavior.AllowGet);

                if (Session["CurrentUser"] is Person person)
                {
                    var applicant = new InvestigatorProxy().InvestigatorChannel.GetTraceBooklet(tracebooklet.ToUpper(), person.PersonId);

                    if (applicant.Booklets.Count == 0)
                        return Json(new { err = "No booklets matching the entered booklet number" }, JsonRequestBehavior.AllowGet);

                    return Json(new { status = 1, page = Helper.JsonPartialView(this, "_TraceBooklet", applicant) }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { status = 0 }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                SaveError(ex);
                return Json(new { status = -1, err = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult SearchByFingerprint(string filename)
        {
            var server = ConfigurationManager.AppSettings["server"];
            var bmp = @"\\" + server + @"\Fingerprints\fingerprint.bmp";
            var wsq = @"\\" + server + @"\Fingerprints\fingerprint.wsq";
            var bmpexists = System.IO.File.Exists(bmp);
            var wsqexists = System.IO.File.Exists(wsq);

            try
            {
                if (string.IsNullOrEmpty(filename))
                {
                    if (bmpexists)
                        filename = bmp;
                    else if (wsqexists)
                        filename = wsq;
                    else
                    {
                        return Json(new { status = -1, err = "Could not find fingerprint image on server" }, JsonRequestBehavior.AllowGet);
                    }
                }

                var matches = new List<Application>();

                // Send to afis
                var url = "http://1.0.1.201/web/request/";

                using (var client = new BetterWebClient(null, false))
                {
                    client.UploadFile(url, filename);
                    var redirect = client.Location;

                    if (!string.IsNullOrEmpty(redirect))
                    {
                        // Try to check for response every second to see if afis has a result for you
                        var tries = 0;
                        while (true)
                        {
                            var response = client.DownloadString(redirect + ".json");

                            dynamic parsedObject = JsonConvert.DeserializeObject(response);
                            if (parsedObject.state == "done")
                            {
                                foreach (var entry in parsedObject.matches)
                                {
                                    var app = new Application()
                                    {
                                        FormNo = entry.form_no,
                                        QueryNo = entry.query_no,
                                        FingerprintPosition = entry.fpos,
                                        Score = entry.score
                                    };

                                    matches.Add(app);
                                }

                                break;
                            }
                            else
                            {
                                // Waiting a maximum of a minute and a half for a response from afis
                                if (tries == 40)
                                    break;

                                // wait 2 second
                                System.Threading.Thread.Sleep(2000);
                                tries++;
                            }
                        }
                    }
                }

                var results = new SearchResults();

                // log audit trail
                var desc = matches.Count == 0 ? "No matches found" : "Idperson: " + string.Join(",", matches.Select(x => x.FormNo).ToArray());
                if (Session["CurrentUser"] is Person person)

EPMS Forensics/Views/Investigator/Index.cshtml
@using EPMS_Forensics_Entities

<link type="text/css" rel="stylesheet" href="~/Content/select2.css" />
<link type="text/css" rel="stylesheet" href="~/Content/jquery-ui.css" />
<link type="text/css" rel="stylesheet" href="~/Content/Investigator/investigator.css" />
<link type="text/css" rel="stylesheet" media="print" href="~/Content/Investigator/investigatorprint.css" />

<script src="~/Scripts/investigator/investigator.js"></script>
<script src="~/Scripts/master/jquery-ui-1.10.4.custom.min.js"></script>
<script src="~/Scripts/master/select2.full.js"></script>

<div class="groupbox">
    <div id="searchagain" class="hidden">
        <div class="button left searchagainbtn">Show Search</div>
        <div class="button left hidden showoptions prevsearchresults">Prev Search Results</div>
        <div id="showoptions" class="button left hidden showoptions">Show Options</div>
        <div class="clear"></div>
    </div>

    <div id="searchcriteria">
        <div id="searchbydiv">
            <div class="left label">Search by:</div>
            <div class="left">
                <select id="selectoptions" class="selectbox">
                    <option></option>
                    @* An Exception for the dashboards. Since we are keeping it permanently logged in, we have to prevent people for using it to do any verifications other than fingerprint *@
                    @if (Session["CurrentUser"] != null && (Session["CurrentUser"] as Person).PersonId == 169)
                    {
                        <option value="searchbyfingerprint">Fingerprint</option>
                    }
                    // Another exception for the CGI
                    @*else if (Session["CurrentUser"] != null && ((Session["CurrentUser"] as EPMS_Forensics_Entities.Person).PersonId == 228 || (Session["CurrentUser"] as EPMS_Forensics_Entities.Person).PersonId == 68))
                        {
                            <option value="searchbyfingerprint">Fingerprint Search</option>
                        }*@
                    else
                    {
                        <option value="searchbymember">Applicant details</option>
                        <option value="searchbyapplication">Application details</option>
                        <option value="searchbyfingerprint">Fingerprint</option>
                        <option value="searchbybooklet">Trace Booklet</option>
                        <option value="searchblacklist">Blacklist</option>
                    }
                </select>
            </div>
            <div class="button left clearbtn">Clear</div>
            <div class="clear"></div>
            <div class="spacedownx2"></div>
        </div>

        @* An Exception for the dashboards. Since we are keeping it permanently logged in, we have to prevent people for using it to do any verifications other than fingerprint *@
        @if (Session["CurrentUser"] != null && (Session["CurrentUser"] as Person).Firstname != "IRIS" && (Session["CurrentUser"] as Person).Surname != "DASHBOARDS")
        {
            <div id="searchbymember" class="searchoption">
                <hr class="hrline" />
                <div class="messagewrap">
                    <div class="message">Please note that all searches done on this tab will henceforth require at least <b>one part of the name</b> and the <b>gender</b> before it can run.</div>
                    @*<div class="message">Temporarily disabled while work being done</div>*@
                    @*<div class="messagSe">Please enter at least <b>TWO</b> variables to search</div>*@
                </div>
                <form method="post" action="@Url.Action("SearchByName", "Investigator")" data-partial="true" data-investigator-search="true" data-target="SearchResults">
                    <div class="left label">Surname</div>
                    @Html.TextBox("surname", null, new { @class = "left textbox" })
                    <div class="clear"></div>

                    <div class="left label">Firstname</div>
                    @Html.TextBox("firstname", null, new { @class = "left textbox" })
                    <div class="clear"></div>

                    <div class="left label">Middlename</div>
                    @Html.TextBox("middlename", null, new { @class = "left textbox" })
                    <div class="clear"></div>

                    <div class="spacetopbot">
                        <div class="left label">Gender</div>
                        <div class="left">
                            @Html.Hidden("sex")
                            <select id="selectgender" class="selectbox">
                                <option></option>
                                <option value="M">Male</option>
                                <option value="F">Female</option>
                            </select>
                        </div>
                        <div class="clear"></div>
                    </div>

                    <div class="left label">Date Of Birth</div>
                    @Html.TextBox("dob", null, new { @class = "left jdpicker lasttextbox", style = "margin", placeholder = "DD/MM/YYYY" })
                    <div class="clear"></div>

                    <div class="spacetop">
                        <div class="left label">Min Age</div>
                        @Html.TextBox("min", null, new { @class = "left textbox spaceright" })
                    </div>

                    <div class="left label">Max Age</div>
                    @Html.TextBox("max", null, new { @class = "left textbox" })
                    <div class="clear"></div>

                    <div class="">
                        <div class="left label">State of Origin</div>
                        <div class="left">
                            @Html.Hidden("state")
                            <select id="stateoforigin" class="selectbox">
                                <option></option>
                                @foreach (State state in ViewBag.States)
                                {
                                    <option value="@state.Name">@state.Name</option>
                                }
                            </select>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="searchbtn">
                        <input type="submit" class="left spacetop button" value="Submit" />
                        <div class="loadingdiv left">
                            <div class="smallmodal"></div>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="errormsg"></div>
                </form>
            </div>

            <div id="searchbyapplication" class="searchoption">
                <hr class="hrline" />
                <form method="post" action="@Url.Action("SearchByApplication", "Investigator")" data-partial="true" data-investigator-search="true" data data-target="SearchResults">
                    <div class="left label">Afisquery Number</div>
                    @Html.TextBox("afisquerynum", null, new { @class = "left textbox", @type = "number" })
                    <div class="clear"></div>

                    <div class="left label">Passport Number</div>
                    @Html.TextBox("passportnum", null, new { @class = "left textbox" })
                    <div class="clear"></div>

                    <div class="left label">ID Person</div>
                    @Html.TextBox("idperson", null, new { @class = "left textbox", @type = "number" })
                    <div class="clear"></div>

                    <div class="left label">Enrolment ID</div>
                    @Html.Hidden("branchid")
                    <div class="left spaceright">
                        <select id="branchNames" class="selectbox left">
                            <option></option>
                            @foreach (Branch branch in ViewBag.Branches)
                            {
                                <option value="@branch.BranchCode">@branch.BranchName</option>
                            }
                        </select>
                    </div>
                    <div class="left spaceright">
                        <select id="branchIds" class="selectbox left">
                            <option></option>
                            @foreach (var branch in (ViewBag.Branches as List<Branch>).OrderBy(x => x.BranchCode))
                            {
                                <option value="@branch.BranchCode">@branch.BranchCode</option>
                            }
                        </select>
                    </div>
                    @Html.TextBox("enrolmentid", null, new { @class = "left textbox lasttextbox width105", @type = "number" })
                    <div class="clear"></div>

                    <div class="searchbtn">
                        <input type="submit" class="left spacetop button" value="Submit" />
                        <div class="loadingdiv left">
                            <div class="smallmodal"></div>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="errormsg"></div>
                </form>
            </div>

            <div id="searchbybooklet" class="searchoption">
                <hr class="hrline" />
                <form method="post" action="@Url.Action("SearchByBooklet", "Investigator")" data-partial="true" data-investigator-search="true" data data-target="SearchResults">
                    <div class="left label">Booklet Number</div>
                    @Html.TextBox("tracebooklet", null, new { @class = "left textbox lasttextbox" })
                    <div class="clear"></div>
                    <div class="searchbtn">
                        <input type="submit" class="left spacetop button" value="Submit" />
                        <div class="loadingdiv left">
                            <div class="smallmodal"></div>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="errormsg"></div>
                </form>
            </div>

            <div id="searchblacklist" class="searchoption">
                <hr class="hrline" />
                <form method="post" action="@Url.Action("SearchBlacklist", "Investigator")" data-partial="true" data-investigator-search="true" data-target="SearchResults">
                    <div class="left label">Passport Number</div>
                    @Html.TextBox("blacklistpassport", null, new { @class = "left textbox" })
                    <div class="clear"></div>
                    <div class="searchbtn">
                        <input type="submit" class="left spacetop button" value="Submit" />
                        <div class="loadingdiv left">
                            <div class="smallmodal"></div>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="errormsg"></div>
                </form>
            </div>
        }

        <div id="searchbyfingerprint" class="searchoption">
            <hr class="hrline" />
            <div class="button collectfingerbtn left">Collect Fingerprint</div>
            <div class="button searchfingerbtn left">Browse for Fingerprint</div>
            <form id="uploader" class="hidden">
                <input id="fileInput" onchange="SearchForFingerprint()" type="file" accept=".bmp, .wsq">
                <input type="submit" value="Upload file" />
            </form>
            <div id="fingerprintload" class="loadingdiv left">
                <div class="smallmodal"></div>
            </div>
            <div class="left searchingafis hidden">Searching AFIS (Depending on AFIS traffic, searches can take as much as 1 minute)</div>
            <div class="clear"></div>
            <div class="errormsg"></div>
        </div>
    </div>

    <div id="SearchResults" class="printable"></div>

    <div id="SelectedDetails"></div>

    <div class="PopupWindow" id="searchFunctions">
        <div class="closebtn">X</div>
        <div class="applicantselected left"></div>
        <div id="searchfunctionloading" class="loadingdiv left">
            <div class="smallmodal"></div>
        </div>
        <div class="clear"></div>

        @Html.Hidden("selectedid")
        @Html.Hidden("selectedformnos")
        <div onclick="DoApplicantFunction(1)" class="button functionoption">View Table Data</div>
        <div onclick="DoApplicantFunction(2)" class="button functionoption">View AFIS Transaction</div>
        <div onclick="DoApplicantFunction(3)" class="button functionoption">View Enrolment History</div>
        <div onclick="DoApplicantFunction(4)" class="button functionoption">View Booklet Page</div>
        <div onclick="DoApplicantFunction(5)" class="button functionoption">View Application Info</div>
    </div>
</div>

EPMS Forensics/Views/Investigator/_BlackList.cshtml
@model List<EPMS_Forensics_Entities.Person>

<div class="searchresultintro spacedownx2">
    @(Model.Count == 1 ? "There is" : "There are") <b class="@(Model.Count == 0 ? "red" : "navy")">
    @(Model.Count)
</b> applicant@(Model.Count == 1 ? "" : "s") that match@(Model.Count == 1 ? "es" : "") your search criteria.
</div>

@if (Model.Count != 0)
{
    <div class="bigheader spacetop">Blacklist Details for <b>@Model[0].Applications[0].DocumentNo</b></div>
    <hr class="hrline" />

    <div class="">
        <div class="label left">Firstname:</div>
        <div class="labeltxt left">@Model[0].FirstNameUpper</div>
        <div class="clear"></div>

        <div class="even">
            <div class="label left">Surname:</div>
            <div class="labeltxt left">@Model[0].SurnameUpper</div>
            <div class="clear"></div>
        </div>

        <div class="label left">Gender:</div>
        <div class="labeltxt left">@(Model[0].Gender == "M" ? "Male" : "Female")</div>
        <div class="clear"></div>

        <div class="even">
            <div class="label left">Date Of Birth:</div>
            <div class="labeltxt left">@Model[0].Dob.ToString("dd-MMM-yyyy")</div>
            <div class="clear"></div>
        </div>

        <div class="label left">Place Of Birth:</div>
        <div class="labeltxt left">@Model[0].PlaceOfBirth</div>
        <div class="clear"></div>

        <div class="even">
            <div class="label left">Reason:</div>
            <div class="labeltxt left firstcapitalise">@Model[0].Applications[0].StageDescription</div>
            <div class="clear"></div>
        </div>

        <div class="label left">Remarks:</div>
        <div class="labeltxt left firstcapitalise">@Model[0].Applications[0].Remarks</div>
        <div class="clear"></div>

        <div class="even">
            <div class="label left">Entry Date:</div>
            <div class="labeltxt left">@Model[0].Applications[0].EnrolDate.ToString("dd/MM/yyyy hh:mm tt").ToLower())</div>
            <div class="clear"></div>
        </div>

        <div class="label left">Last Update:</div>
        <div class="labeltxt left">@Model[0].Applications[0].ExpiryDate.ToString("dd/MM/yyyy hh:mm tt").ToLower())</div>
        <div class="clear"></div>

        <div class="even">
            <div class="label left">Effective Date:</div>
            <div class="labeltxt left">@Model[0].Applications[0].IssueDate.ToString("dd/MM/yyyy hh:mm tt").ToLower())</div>
            <div class="clear"></div>
        </div>
    </div>
}

EPMS Forensics/Views/Investigator/_SearchResults.cshtml
@model EPMS_Forensics.Models.Investigator.SearchResults

<div class="searchresultintro spacedownx2">@(Model.Applicants.Count == 1 ? "There is" : "There are") <b class="@(Model.Applicants.Count == 0 ? "red" : "navy")">
@(Model.Applicants.Count)</b> applicant@(Model.Applicants.Count == 1 ? "" : "s") that match@(Model.Applicants.Count == 1 ? "es" : "") your search criteria.</div>

@if (Model.Applicants.Count != 0)
{ 
    <div class="table shadow">
        <div class="tablediv">
            <div class="tableheader">
                <div class="serialno">S/N</div>
                <div class="applicantinfo">Applicant Information (S/F/M)</div>
                <div class="appdob">Gender</div>
                <div class="appcounts">Counts</div>
                <div class="appdob">DOB</div>
                <div class="appformno">IdPerson</div>
                <div class="apptype">Type</div>
            </div>

            @for(var x = 1; x < Model.Applicants.Count + 1; x++)
            {
                var applicant = Model.Applicants[x - 1];
                <div id="@(applicant.IdPerson)" class="applicantselection @(x % 2 == 0 ? "even" : "")">
                    @Html.Hidden("formno", string.Join(",", applicant.FormNoList.ToArray()))
                    <div class="serialno">@(x)</div>
                    <div class="applicantinfo">@applicant.SurnameUpper @applicant.FirstNameUpper @applicant.MiddlenameUpper</div>
                    <div class="appdob">@applicant.Gender</div>
                    <div class="appcounts">@applicant.FormNoList.Count</div>
                    <div class="appdob">@(applicant.Dob == DateTime.MinValue ? "Pending" : applicant.Dob.ToString("dd/MM/yyyy"))</div>
                    <div class="appformno">@applicant.IdPerson</div>
                    <div class="apptype">@applicant.AppType</div>
                </div>
            }
        </div>
    </div>
}

EPMS Forensics/Views/Investigator/_ViewAfisTransaction.cshtml
@using EPMS_Forensics_Entities
@model List<Person>

@if (Model.Count > 1)
{
    <div class="nextprevdiv right">
        @Html.Hidden("currentpassport", 1)
        @Html.Hidden("totalpassports", Model.Count)
        <div class="prev disabled button left">Prev</div>
        <div class="left countinfo">1 of @(Model.Count)</div>
        <div class="next button left">Next</div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
}

@if (string.IsNullOrEmpty(Model[0].AfisRecords[0].FormNo))
{
     <div class="centeredmsg">No AFIS Record Found</div>
}
else
{ 
    for (var x = 0; x < Model.Count; x++)
    {
        <div id="application@(x+1)" class="@(x > 0 ? "hidden" : "")">
            <div class="bigformno">@Model[x].FirstNameUpper @Model[x].MiddlenameUpper @Model[x].SurnameUpper: <b>Form No - @Model[x].AfisRecords[0].FormNo</b></div>
            <div class="table shadow">
                <div class="tablediv">
                    <div class="tableheader fifteenpercent">
                        <div class="dmltype">DML Type</div>
                        <div class="stagecode">Stage Code</div>
                        <div class="adtdate">ADT Date</div>
                        <div class="remarks">Remarks</div>
                        <div class="olddocno">Old Doc No</div>
                        <div class="flag1">Flag 1</div>
                        <div class="flag2">Flag 2</div>
                    </div>

                    @for (var y = 1; y < Model[x].AfisRecords.Count + 1; y++)
                    {
                        var transaction = Model[x].AfisRecords[y - 1];
                        <div class="fifteenpercent @(y % 2 == 0 ? "even" : "")">
                            <div class="dmltype">@transaction.DmlType</div>
                            <div class="stagecode">@transaction.StageCode</div>
                            <div class="adtdate">@transaction.AdtDate</div>
                            <div class="remarks">@transaction.Remarks</div>
                            <div class="olddocno">@transaction.OldDocNumber</div>
                            <div class="flag1">@transaction.Flag1</div>
                            <div class="flag2">@transaction.Flag2</div>
                        </div>
                    }
                </div>
            </div>
        </div>
    }
}